// AUTO-GENERATED by scripts/write_build_info.py — do not edit by hand.
globalThis.__JA_BUILD_INFO__ = {
  "shortSha": "0ca25ff",
  "sourceSha": "0ca25ff",
  "sha": "0ca25ffba54967715163b75656e25559e77ede47",
  "branch": "stage1/slim-autofill",
  "committedAt": "2026-07-25T13:47:12-04:00",
  "generatedAt": "2026-07-25T13:47:12-04:00"
};
