// AUTO-GENERATED by scripts/write_build_info.py — do not edit by hand.
globalThis.__JA_BUILD_INFO__ = {
  "shortSha": "6195cc8",
  "sourceSha": "6195cc8",
  "sha": "6195cc888b57329b48bd2f8601a6f23e4188955f",
  "branch": "stage1/slim-autofill",
  "committedAt": "2026-07-25T14:47:14-04:00",
  "generatedAt": "2026-07-25T14:47:14-04:00"
};
