// AUTO-GENERATED by scripts/write_build_info.py — do not edit by hand.
globalThis.__JA_BUILD_INFO__ = {
  "shortSha": "43ecc83",
  "sourceSha": "43ecc83",
  "sha": "43ecc83455b10612a30b07591d1c8814e05e212e",
  "branch": "stage1/slim-autofill",
  "committedAt": "2026-07-25T14:41:40-04:00",
  "generatedAt": "2026-07-25T14:41:40-04:00"
};
