# AUTO-GENERATED by scripts/write_build_info.py — do not edit by hand.
SHORT_SHA = "cb49282"
SOURCE_SHA = "cb49282"
SHA = "cb49282182b7a602644521846dc9648efdb8d457"
BRANCH = "stage1/slim-autofill"
COMMITTED_AT = "2026-07-25T14:31:51-04:00"
