# AUTO-GENERATED by scripts/write_build_info.py — do not edit by hand.
SHORT_SHA = "0ca25ff"
SOURCE_SHA = "0ca25ff"
SHA = "0ca25ffba54967715163b75656e25559e77ede47"
BRANCH = "stage1/slim-autofill"
COMMITTED_AT = "2026-07-25T13:47:12-04:00"
