#!/usr/bin/env python3
"""Generate extension/build-info.js and app/build_info.py from the checked-out Git commit.

Writes both:
  - sourceSha: the commit that produced the packaged sources (HEAD at generation)
  - tipSha: same as sourceSha at generation time

Backend /api/meta prefers a live `git rev-parse` at process start so the
running server identity matches the checkout without stamp-lag commits.
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def _git(*args: str) -> str:
    try:
        out = subprocess.check_output(
            ["git", *args],
            cwd=ROOT,
            stderr=subprocess.DEVNULL,
            text=True,
        )
        return out.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return ""


def main() -> int:
    short = _git("rev-parse", "--short", "HEAD") or "unknown"
    full = _git("rev-parse", "HEAD") or "unknown"
    branch = _git("rev-parse", "--abbrev-ref", "HEAD") or "unknown"
    committed = _git("log", "-1", "--format=%cI") or ""

    payload = {
        "shortSha": short,
        "sourceSha": short,
        "sha": full,
        "branch": branch,
        "committedAt": committed,
        "generatedAt": committed,
    }

    js_path = ROOT / "extension" / "build-info.js"
    js_path.write_text(
        "// AUTO-GENERATED by scripts/write_build_info.py — do not edit by hand.\n"
        f"globalThis.__JA_BUILD_INFO__ = {json.dumps(payload, indent=2)};\n",
        encoding="utf-8",
    )

    py_path = ROOT / "app" / "build_info.py"
    py_path.write_text(
        '# AUTO-GENERATED by scripts/write_build_info.py — do not edit by hand.\n'
        f'SHORT_SHA = {json.dumps(short)}\n'
        f'SOURCE_SHA = {json.dumps(short)}\n'
        f'SHA = {json.dumps(full)}\n'
        f'BRANCH = {json.dumps(branch)}\n'
        f'COMMITTED_AT = {json.dumps(committed)}\n',
        encoding="utf-8",
    )

    print(f"Wrote build info: sourceSha={short} ({branch})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
